version: "3.9"
services:
  sparklebot:
    container_name: sparklebot
    build:
      context: .
      dockerfile: Dockerfile
    image: docker-nexus.puppyfire.net/puppyfire/sparklebot:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Production