/*
 * Open WebUI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing AddPipelineForm
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AddPipelineFormTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AddPipelineForm
        //private AddPipelineForm instance;

        public AddPipelineFormTests()
        {
            // TODO uncomment below to create an instance of AddPipelineForm
            //instance = new AddPipelineForm();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AddPipelineForm
        /// </summary>
        [Fact]
        public void AddPipelineFormInstanceTest()
        {
            // TODO uncomment below to test "IsType" AddPipelineForm
            //Assert.IsType<AddPipelineForm>(instance);
        }

        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Fact]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }

        /// <summary>
        /// Test the property 'UrlIdx'
        /// </summary>
        [Fact]
        public void UrlIdxTest()
        {
            // TODO unit test for the property 'UrlIdx'
        }
    }
}
