/*
 * Open WebUI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing ChatPermissions
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ChatPermissionsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ChatPermissions
        //private ChatPermissions instance;

        public ChatPermissionsTests()
        {
            // TODO uncomment below to create an instance of ChatPermissions
            //instance = new ChatPermissions();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ChatPermissions
        /// </summary>
        [Fact]
        public void ChatPermissionsInstanceTest()
        {
            // TODO uncomment below to test "IsType" ChatPermissions
            //Assert.IsType<ChatPermissions>(instance);
        }

        /// <summary>
        /// Test the property 'Controls'
        /// </summary>
        [Fact]
        public void ControlsTest()
        {
            // TODO unit test for the property 'Controls'
        }

        /// <summary>
        /// Test the property 'SystemPrompt'
        /// </summary>
        [Fact]
        public void SystemPromptTest()
        {
            // TODO unit test for the property 'SystemPrompt'
        }

        /// <summary>
        /// Test the property 'FileUpload'
        /// </summary>
        [Fact]
        public void FileUploadTest()
        {
            // TODO unit test for the property 'FileUpload'
        }

        /// <summary>
        /// Test the property 'Delete'
        /// </summary>
        [Fact]
        public void DeleteTest()
        {
            // TODO unit test for the property 'Delete'
        }

        /// <summary>
        /// Test the property 'Edit'
        /// </summary>
        [Fact]
        public void EditTest()
        {
            // TODO unit test for the property 'Edit'
        }

        /// <summary>
        /// Test the property 'Share'
        /// </summary>
        [Fact]
        public void ShareTest()
        {
            // TODO unit test for the property 'Share'
        }

        /// <summary>
        /// Test the property 'Export'
        /// </summary>
        [Fact]
        public void ExportTest()
        {
            // TODO unit test for the property 'Export'
        }

        /// <summary>
        /// Test the property 'Stt'
        /// </summary>
        [Fact]
        public void SttTest()
        {
            // TODO unit test for the property 'Stt'
        }

        /// <summary>
        /// Test the property 'Tts'
        /// </summary>
        [Fact]
        public void TtsTest()
        {
            // TODO unit test for the property 'Tts'
        }

        /// <summary>
        /// Test the property 'Call'
        /// </summary>
        [Fact]
        public void CallTest()
        {
            // TODO unit test for the property 'Call'
        }

        /// <summary>
        /// Test the property 'MultipleModels'
        /// </summary>
        [Fact]
        public void MultipleModelsTest()
        {
            // TODO unit test for the property 'MultipleModels'
        }

        /// <summary>
        /// Test the property 'Temporary'
        /// </summary>
        [Fact]
        public void TemporaryTest()
        {
            // TODO unit test for the property 'Temporary'
        }

        /// <summary>
        /// Test the property 'TemporaryEnforced'
        /// </summary>
        [Fact]
        public void TemporaryEnforcedTest()
        {
            // TODO unit test for the property 'TemporaryEnforced'
        }
    }
}
