/*
 * Open WebUI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing ComfyUIConfigForm
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ComfyUIConfigFormTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ComfyUIConfigForm
        //private ComfyUIConfigForm instance;

        public ComfyUIConfigFormTests()
        {
            // TODO uncomment below to create an instance of ComfyUIConfigForm
            //instance = new ComfyUIConfigForm();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ComfyUIConfigForm
        /// </summary>
        [Fact]
        public void ComfyUIConfigFormInstanceTest()
        {
            // TODO uncomment below to test "IsType" ComfyUIConfigForm
            //Assert.IsType<ComfyUIConfigForm>(instance);
        }

        /// <summary>
        /// Test the property 'COMFYUI_BASE_URL'
        /// </summary>
        [Fact]
        public void COMFYUI_BASE_URLTest()
        {
            // TODO unit test for the property 'COMFYUI_BASE_URL'
        }

        /// <summary>
        /// Test the property 'COMFYUI_API_KEY'
        /// </summary>
        [Fact]
        public void COMFYUI_API_KEYTest()
        {
            // TODO unit test for the property 'COMFYUI_API_KEY'
        }

        /// <summary>
        /// Test the property 'COMFYUI_WORKFLOW'
        /// </summary>
        [Fact]
        public void COMFYUI_WORKFLOWTest()
        {
            // TODO unit test for the property 'COMFYUI_WORKFLOW'
        }

        /// <summary>
        /// Test the property 'COMFYUI_WORKFLOW_NODES'
        /// </summary>
        [Fact]
        public void COMFYUI_WORKFLOW_NODESTest()
        {
            // TODO unit test for the property 'COMFYUI_WORKFLOW_NODES'
        }
    }
}
