/*
 * Open WebUI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing DeleteForm
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DeleteFormTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DeleteForm
        //private DeleteForm instance;

        public DeleteFormTests()
        {
            // TODO uncomment below to create an instance of DeleteForm
            //instance = new DeleteForm();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DeleteForm
        /// </summary>
        [Fact]
        public void DeleteFormInstanceTest()
        {
            // TODO uncomment below to test "IsType" DeleteForm
            //Assert.IsType<DeleteForm>(instance);
        }

        /// <summary>
        /// Test the property 'CollectionName'
        /// </summary>
        [Fact]
        public void CollectionNameTest()
        {
            // TODO unit test for the property 'CollectionName'
        }

        /// <summary>
        /// Test the property 'FileId'
        /// </summary>
        [Fact]
        public void FileIdTest()
        {
            // TODO unit test for the property 'FileId'
        }
    }
}
