/*
 * Open WebUI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing DirectConnectionsConfigForm
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DirectConnectionsConfigFormTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DirectConnectionsConfigForm
        //private DirectConnectionsConfigForm instance;

        public DirectConnectionsConfigFormTests()
        {
            // TODO uncomment below to create an instance of DirectConnectionsConfigForm
            //instance = new DirectConnectionsConfigForm();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DirectConnectionsConfigForm
        /// </summary>
        [Fact]
        public void DirectConnectionsConfigFormInstanceTest()
        {
            // TODO uncomment below to test "IsType" DirectConnectionsConfigForm
            //Assert.IsType<DirectConnectionsConfigForm>(instance);
        }

        /// <summary>
        /// Test the property 'ENABLE_DIRECT_CONNECTIONS'
        /// </summary>
        [Fact]
        public void ENABLE_DIRECT_CONNECTIONSTest()
        {
            // TODO unit test for the property 'ENABLE_DIRECT_CONNECTIONS'
        }
    }
}
