/*
 * Open WebUI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing LoadUrlForm
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class LoadUrlFormTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for LoadUrlForm
        //private LoadUrlForm instance;

        public LoadUrlFormTests()
        {
            // TODO uncomment below to create an instance of LoadUrlForm
            //instance = new LoadUrlForm();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of LoadUrlForm
        /// </summary>
        [Fact]
        public void LoadUrlFormInstanceTest()
        {
            // TODO uncomment below to test "IsType" LoadUrlForm
            //Assert.IsType<LoadUrlForm>(instance);
        }

        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Fact]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }
    }
}
