/*
 * Open WebUI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing OpenWebuiRoutersOpenaiConnectionVerificationForm
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OpenWebuiRoutersOpenaiConnectionVerificationFormTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OpenWebuiRoutersOpenaiConnectionVerificationForm
        //private OpenWebuiRoutersOpenaiConnectionVerificationForm instance;

        public OpenWebuiRoutersOpenaiConnectionVerificationFormTests()
        {
            // TODO uncomment below to create an instance of OpenWebuiRoutersOpenaiConnectionVerificationForm
            //instance = new OpenWebuiRoutersOpenaiConnectionVerificationForm();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OpenWebuiRoutersOpenaiConnectionVerificationForm
        /// </summary>
        [Fact]
        public void OpenWebuiRoutersOpenaiConnectionVerificationFormInstanceTest()
        {
            // TODO uncomment below to test "IsType" OpenWebuiRoutersOpenaiConnectionVerificationForm
            //Assert.IsType<OpenWebuiRoutersOpenaiConnectionVerificationForm>(instance);
        }

        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Fact]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }

        /// <summary>
        /// Test the property 'Key'
        /// </summary>
        [Fact]
        public void KeyTest()
        {
            // TODO unit test for the property 'Key'
        }

        /// <summary>
        /// Test the property 'Config'
        /// </summary>
        [Fact]
        public void ConfigTest()
        {
            // TODO unit test for the property 'Config'
        }
    }
}
