/*
 * Open WebUI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing OpenWebuiRoutersChatsMessageForm
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OpenWebuiRoutersChatsMessageFormTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OpenWebuiRoutersChatsMessageForm
        //private OpenWebuiRoutersChatsMessageForm instance;

        public OpenWebuiRoutersChatsMessageFormTests()
        {
            // TODO uncomment below to create an instance of OpenWebuiRoutersChatsMessageForm
            //instance = new OpenWebuiRoutersChatsMessageForm();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OpenWebuiRoutersChatsMessageForm
        /// </summary>
        [Fact]
        public void OpenWebuiRoutersChatsMessageFormInstanceTest()
        {
            // TODO uncomment below to test "IsType" OpenWebuiRoutersChatsMessageForm
            //Assert.IsType<OpenWebuiRoutersChatsMessageForm>(instance);
        }

        /// <summary>
        /// Test the property 'Content'
        /// </summary>
        [Fact]
        public void ContentTest()
        {
            // TODO unit test for the property 'Content'
        }
    }
}
