/*
 * Open WebUI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing OpenWebuiRoutersOllamaOllamaConfigForm
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OpenWebuiRoutersOllamaOllamaConfigFormTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OpenWebuiRoutersOllamaOllamaConfigForm
        //private OpenWebuiRoutersOllamaOllamaConfigForm instance;

        public OpenWebuiRoutersOllamaOllamaConfigFormTests()
        {
            // TODO uncomment below to create an instance of OpenWebuiRoutersOllamaOllamaConfigForm
            //instance = new OpenWebuiRoutersOllamaOllamaConfigForm();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OpenWebuiRoutersOllamaOllamaConfigForm
        /// </summary>
        [Fact]
        public void OpenWebuiRoutersOllamaOllamaConfigFormInstanceTest()
        {
            // TODO uncomment below to test "IsType" OpenWebuiRoutersOllamaOllamaConfigForm
            //Assert.IsType<OpenWebuiRoutersOllamaOllamaConfigForm>(instance);
        }

        /// <summary>
        /// Test the property 'OLLAMA_BASE_URLS'
        /// </summary>
        [Fact]
        public void OLLAMA_BASE_URLSTest()
        {
            // TODO unit test for the property 'OLLAMA_BASE_URLS'
        }

        /// <summary>
        /// Test the property 'OLLAMA_API_CONFIGS'
        /// </summary>
        [Fact]
        public void OLLAMA_API_CONFIGSTest()
        {
            // TODO unit test for the property 'OLLAMA_API_CONFIGS'
        }

        /// <summary>
        /// Test the property 'ENABLE_OLLAMA_API'
        /// </summary>
        [Fact]
        public void ENABLE_OLLAMA_APITest()
        {
            // TODO unit test for the property 'ENABLE_OLLAMA_API'
        }
    }
}
