/*
 * Open WebUI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing PromptForm
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PromptFormTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PromptForm
        //private PromptForm instance;

        public PromptFormTests()
        {
            // TODO uncomment below to create an instance of PromptForm
            //instance = new PromptForm();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PromptForm
        /// </summary>
        [Fact]
        public void PromptFormInstanceTest()
        {
            // TODO uncomment below to test "IsType" PromptForm
            //Assert.IsType<PromptForm>(instance);
        }

        /// <summary>
        /// Test the property 'Command'
        /// </summary>
        [Fact]
        public void CommandTest()
        {
            // TODO unit test for the property 'Command'
        }

        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Fact]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }

        /// <summary>
        /// Test the property 'Content'
        /// </summary>
        [Fact]
        public void ContentTest()
        {
            // TODO unit test for the property 'Content'
        }

        /// <summary>
        /// Test the property 'AccessControl'
        /// </summary>
        [Fact]
        public void AccessControlTest()
        {
            // TODO unit test for the property 'AccessControl'
        }
    }
}
