/*
 * Open WebUI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing Reason
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ReasonTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Reason
        //private Reason instance;

        public ReasonTests()
        {
            // TODO uncomment below to create an instance of Reason
            //instance = new Reason();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Reason
        /// </summary>
        [Fact]
        public void ReasonInstanceTest()
        {
            // TODO uncomment below to test "IsType" Reason
            //Assert.IsType<Reason>(instance);
        }
    }
}
