/*
 * Open WebUI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing TagFilterForm
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TagFilterFormTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TagFilterForm
        //private TagFilterForm instance;

        public TagFilterFormTests()
        {
            // TODO uncomment below to create an instance of TagFilterForm
            //instance = new TagFilterForm();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TagFilterForm
        /// </summary>
        [Fact]
        public void TagFilterFormInstanceTest()
        {
            // TODO uncomment below to test "IsType" TagFilterForm
            //Assert.IsType<TagFilterForm>(instance);
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Skip'
        /// </summary>
        [Fact]
        public void SkipTest()
        {
            // TODO unit test for the property 'Skip'
        }

        /// <summary>
        /// Test the property 'Limit'
        /// </summary>
        [Fact]
        public void LimitTest()
        {
            // TODO unit test for the property 'Limit'
        }
    }
}
