// <auto-generated>
/*
 * Open WebUI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// ChatFolderIdForm
    /// </summary>
    public partial class ChatFolderIdForm : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ChatFolderIdForm" /> class.
        /// </summary>
        /// <param name="folderId">folderId</param>
        [JsonConstructor]
        public ChatFolderIdForm(Option<string?> folderId = default)
        {
            FolderIdOption = folderId;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of FolderId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> FolderIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets FolderId
        /// </summary>
        [JsonPropertyName("folder_id")]
        public string? FolderId { get { return this.FolderIdOption; } set { this.FolderIdOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ChatFolderIdForm {\n");
            sb.Append("  FolderId: ").Append(FolderId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ChatFolderIdForm" />
    /// </summary>
    public class ChatFolderIdFormJsonConverter : JsonConverter<ChatFolderIdForm>
    {
        /// <summary>
        /// Deserializes json to <see cref="ChatFolderIdForm" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ChatFolderIdForm Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> folderId = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "folder_id":
                            folderId = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        default:
                            break;
                    }
                }
            }

            return new ChatFolderIdForm(folderId);
        }

        /// <summary>
        /// Serializes a <see cref="ChatFolderIdForm" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="chatFolderIdForm"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ChatFolderIdForm chatFolderIdForm, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, chatFolderIdForm, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ChatFolderIdForm" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="chatFolderIdForm"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ChatFolderIdForm chatFolderIdForm, JsonSerializerOptions jsonSerializerOptions)
        {
            if (chatFolderIdForm.FolderIdOption.IsSet)
                if (chatFolderIdForm.FolderIdOption.Value != null)
                    writer.WriteString("folder_id", chatFolderIdForm.FolderId);
                else
                    writer.WriteNull("folder_id");
        }
    }
}
