// <auto-generated>
/*
 * Open WebUI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// GeminiConfigForm
    /// </summary>
    public partial class GeminiConfigForm : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GeminiConfigForm" /> class.
        /// </summary>
        /// <param name="gEMINIAPIBASEURL">gEMINIAPIBASEURL</param>
        /// <param name="gEMINIAPIKEY">gEMINIAPIKEY</param>
        [JsonConstructor]
        public GeminiConfigForm(string gEMINIAPIBASEURL, string gEMINIAPIKEY)
        {
            GEMINI_API_BASE_URL = gEMINIAPIBASEURL;
            GEMINI_API_KEY = gEMINIAPIKEY;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets GEMINI_API_BASE_URL
        /// </summary>
        [JsonPropertyName("GEMINI_API_BASE_URL")]
        public string GEMINI_API_BASE_URL { get; set; }

        /// <summary>
        /// Gets or Sets GEMINI_API_KEY
        /// </summary>
        [JsonPropertyName("GEMINI_API_KEY")]
        public string GEMINI_API_KEY { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GeminiConfigForm {\n");
            sb.Append("  GEMINI_API_BASE_URL: ").Append(GEMINI_API_BASE_URL).Append("\n");
            sb.Append("  GEMINI_API_KEY: ").Append(GEMINI_API_KEY).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="GeminiConfigForm" />
    /// </summary>
    public class GeminiConfigFormJsonConverter : JsonConverter<GeminiConfigForm>
    {
        /// <summary>
        /// Deserializes json to <see cref="GeminiConfigForm" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override GeminiConfigForm Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> gEMINIAPIBASEURL = default;
            Option<string?> gEMINIAPIKEY = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "GEMINI_API_BASE_URL":
                            gEMINIAPIBASEURL = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "GEMINI_API_KEY":
                            gEMINIAPIKEY = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!gEMINIAPIBASEURL.IsSet)
                throw new ArgumentException("Property is required for class GeminiConfigForm.", nameof(gEMINIAPIBASEURL));

            if (!gEMINIAPIKEY.IsSet)
                throw new ArgumentException("Property is required for class GeminiConfigForm.", nameof(gEMINIAPIKEY));

            if (gEMINIAPIBASEURL.IsSet && gEMINIAPIBASEURL.Value == null)
                throw new ArgumentNullException(nameof(gEMINIAPIBASEURL), "Property is not nullable for class GeminiConfigForm.");

            if (gEMINIAPIKEY.IsSet && gEMINIAPIKEY.Value == null)
                throw new ArgumentNullException(nameof(gEMINIAPIKEY), "Property is not nullable for class GeminiConfigForm.");

            return new GeminiConfigForm(gEMINIAPIBASEURL.Value!, gEMINIAPIKEY.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="GeminiConfigForm" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="geminiConfigForm"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, GeminiConfigForm geminiConfigForm, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, geminiConfigForm, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="GeminiConfigForm" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="geminiConfigForm"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, GeminiConfigForm geminiConfigForm, JsonSerializerOptions jsonSerializerOptions)
        {
            if (geminiConfigForm.GEMINI_API_BASE_URL == null)
                throw new ArgumentNullException(nameof(geminiConfigForm.GEMINI_API_BASE_URL), "Property is required for class GeminiConfigForm.");

            if (geminiConfigForm.GEMINI_API_KEY == null)
                throw new ArgumentNullException(nameof(geminiConfigForm.GEMINI_API_KEY), "Property is required for class GeminiConfigForm.");

            writer.WriteString("GEMINI_API_BASE_URL", geminiConfigForm.GEMINI_API_BASE_URL);

            writer.WriteString("GEMINI_API_KEY", geminiConfigForm.GEMINI_API_KEY);
        }
    }
}
