// <auto-generated>
/*
 * Open WebUI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// OpenWebuiModelsUsersUserResponse
    /// </summary>
    public partial class OpenWebuiModelsUsersUserResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="OpenWebuiModelsUsersUserResponse" /> class.
        /// </summary>
        /// <param name="id">id</param>
        /// <param name="email">email</param>
        /// <param name="name">name</param>
        /// <param name="role">role</param>
        /// <param name="profileImageUrl">profileImageUrl</param>
        [JsonConstructor]
        public OpenWebuiModelsUsersUserResponse(string id, string email, string name, string role, string profileImageUrl)
        {
            Id = id;
            Email = email;
            Name = name;
            Role = role;
            ProfileImageUrl = profileImageUrl;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [JsonPropertyName("id")]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets Email
        /// </summary>
        [JsonPropertyName("email")]
        public string Email { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [JsonPropertyName("name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets Role
        /// </summary>
        [JsonPropertyName("role")]
        public string Role { get; set; }

        /// <summary>
        /// Gets or Sets ProfileImageUrl
        /// </summary>
        [JsonPropertyName("profile_image_url")]
        public string ProfileImageUrl { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class OpenWebuiModelsUsersUserResponse {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Email: ").Append(Email).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Role: ").Append(Role).Append("\n");
            sb.Append("  ProfileImageUrl: ").Append(ProfileImageUrl).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="OpenWebuiModelsUsersUserResponse" />
    /// </summary>
    public class OpenWebuiModelsUsersUserResponseJsonConverter : JsonConverter<OpenWebuiModelsUsersUserResponse>
    {
        /// <summary>
        /// Deserializes json to <see cref="OpenWebuiModelsUsersUserResponse" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override OpenWebuiModelsUsersUserResponse Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> id = default;
            Option<string?> email = default;
            Option<string?> name = default;
            Option<string?> role = default;
            Option<string?> profileImageUrl = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "id":
                            id = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "email":
                            email = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "name":
                            name = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "role":
                            role = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "profile_image_url":
                            profileImageUrl = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!id.IsSet)
                throw new ArgumentException("Property is required for class OpenWebuiModelsUsersUserResponse.", nameof(id));

            if (!email.IsSet)
                throw new ArgumentException("Property is required for class OpenWebuiModelsUsersUserResponse.", nameof(email));

            if (!name.IsSet)
                throw new ArgumentException("Property is required for class OpenWebuiModelsUsersUserResponse.", nameof(name));

            if (!role.IsSet)
                throw new ArgumentException("Property is required for class OpenWebuiModelsUsersUserResponse.", nameof(role));

            if (!profileImageUrl.IsSet)
                throw new ArgumentException("Property is required for class OpenWebuiModelsUsersUserResponse.", nameof(profileImageUrl));

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class OpenWebuiModelsUsersUserResponse.");

            if (email.IsSet && email.Value == null)
                throw new ArgumentNullException(nameof(email), "Property is not nullable for class OpenWebuiModelsUsersUserResponse.");

            if (name.IsSet && name.Value == null)
                throw new ArgumentNullException(nameof(name), "Property is not nullable for class OpenWebuiModelsUsersUserResponse.");

            if (role.IsSet && role.Value == null)
                throw new ArgumentNullException(nameof(role), "Property is not nullable for class OpenWebuiModelsUsersUserResponse.");

            if (profileImageUrl.IsSet && profileImageUrl.Value == null)
                throw new ArgumentNullException(nameof(profileImageUrl), "Property is not nullable for class OpenWebuiModelsUsersUserResponse.");

            return new OpenWebuiModelsUsersUserResponse(id.Value!, email.Value!, name.Value!, role.Value!, profileImageUrl.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="OpenWebuiModelsUsersUserResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="openWebuiModelsUsersUserResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, OpenWebuiModelsUsersUserResponse openWebuiModelsUsersUserResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, openWebuiModelsUsersUserResponse, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="OpenWebuiModelsUsersUserResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="openWebuiModelsUsersUserResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, OpenWebuiModelsUsersUserResponse openWebuiModelsUsersUserResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            if (openWebuiModelsUsersUserResponse.Id == null)
                throw new ArgumentNullException(nameof(openWebuiModelsUsersUserResponse.Id), "Property is required for class OpenWebuiModelsUsersUserResponse.");

            if (openWebuiModelsUsersUserResponse.Email == null)
                throw new ArgumentNullException(nameof(openWebuiModelsUsersUserResponse.Email), "Property is required for class OpenWebuiModelsUsersUserResponse.");

            if (openWebuiModelsUsersUserResponse.Name == null)
                throw new ArgumentNullException(nameof(openWebuiModelsUsersUserResponse.Name), "Property is required for class OpenWebuiModelsUsersUserResponse.");

            if (openWebuiModelsUsersUserResponse.Role == null)
                throw new ArgumentNullException(nameof(openWebuiModelsUsersUserResponse.Role), "Property is required for class OpenWebuiModelsUsersUserResponse.");

            if (openWebuiModelsUsersUserResponse.ProfileImageUrl == null)
                throw new ArgumentNullException(nameof(openWebuiModelsUsersUserResponse.ProfileImageUrl), "Property is required for class OpenWebuiModelsUsersUserResponse.");

            writer.WriteString("id", openWebuiModelsUsersUserResponse.Id);

            writer.WriteString("email", openWebuiModelsUsersUserResponse.Email);

            writer.WriteString("name", openWebuiModelsUsersUserResponse.Name);

            writer.WriteString("role", openWebuiModelsUsersUserResponse.Role);

            writer.WriteString("profile_image_url", openWebuiModelsUsersUserResponse.ProfileImageUrl);
        }
    }
}
