// <auto-generated>
/*
 * Open WebUI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// OpenWebuiRoutersRetrievalOllamaConfigForm
    /// </summary>
    public partial class OpenWebuiRoutersRetrievalOllamaConfigForm : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="OpenWebuiRoutersRetrievalOllamaConfigForm" /> class.
        /// </summary>
        /// <param name="url">url</param>
        /// <param name="key">key</param>
        [JsonConstructor]
        public OpenWebuiRoutersRetrievalOllamaConfigForm(string url, string key)
        {
            Url = url;
            Key = key;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Url
        /// </summary>
        [JsonPropertyName("url")]
        public string Url { get; set; }

        /// <summary>
        /// Gets or Sets Key
        /// </summary>
        [JsonPropertyName("key")]
        public string Key { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class OpenWebuiRoutersRetrievalOllamaConfigForm {\n");
            sb.Append("  Url: ").Append(Url).Append("\n");
            sb.Append("  Key: ").Append(Key).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="OpenWebuiRoutersRetrievalOllamaConfigForm" />
    /// </summary>
    public class OpenWebuiRoutersRetrievalOllamaConfigFormJsonConverter : JsonConverter<OpenWebuiRoutersRetrievalOllamaConfigForm>
    {
        /// <summary>
        /// Deserializes json to <see cref="OpenWebuiRoutersRetrievalOllamaConfigForm" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override OpenWebuiRoutersRetrievalOllamaConfigForm Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> url = default;
            Option<string?> key = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "url":
                            url = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "key":
                            key = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!url.IsSet)
                throw new ArgumentException("Property is required for class OpenWebuiRoutersRetrievalOllamaConfigForm.", nameof(url));

            if (!key.IsSet)
                throw new ArgumentException("Property is required for class OpenWebuiRoutersRetrievalOllamaConfigForm.", nameof(key));

            if (url.IsSet && url.Value == null)
                throw new ArgumentNullException(nameof(url), "Property is not nullable for class OpenWebuiRoutersRetrievalOllamaConfigForm.");

            if (key.IsSet && key.Value == null)
                throw new ArgumentNullException(nameof(key), "Property is not nullable for class OpenWebuiRoutersRetrievalOllamaConfigForm.");

            return new OpenWebuiRoutersRetrievalOllamaConfigForm(url.Value!, key.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="OpenWebuiRoutersRetrievalOllamaConfigForm" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="openWebuiRoutersRetrievalOllamaConfigForm"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, OpenWebuiRoutersRetrievalOllamaConfigForm openWebuiRoutersRetrievalOllamaConfigForm, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, openWebuiRoutersRetrievalOllamaConfigForm, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="OpenWebuiRoutersRetrievalOllamaConfigForm" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="openWebuiRoutersRetrievalOllamaConfigForm"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, OpenWebuiRoutersRetrievalOllamaConfigForm openWebuiRoutersRetrievalOllamaConfigForm, JsonSerializerOptions jsonSerializerOptions)
        {
            if (openWebuiRoutersRetrievalOllamaConfigForm.Url == null)
                throw new ArgumentNullException(nameof(openWebuiRoutersRetrievalOllamaConfigForm.Url), "Property is required for class OpenWebuiRoutersRetrievalOllamaConfigForm.");

            if (openWebuiRoutersRetrievalOllamaConfigForm.Key == null)
                throw new ArgumentNullException(nameof(openWebuiRoutersRetrievalOllamaConfigForm.Key), "Property is required for class OpenWebuiRoutersRetrievalOllamaConfigForm.");

            writer.WriteString("url", openWebuiRoutersRetrievalOllamaConfigForm.Url);

            writer.WriteString("key", openWebuiRoutersRetrievalOllamaConfigForm.Key);
        }
    }
}
