// <auto-generated>
/*
 * Open WebUI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// OpenWebuiRoutersOllamaOllamaConfigForm
    /// </summary>
    public partial class OpenWebuiRoutersOllamaOllamaConfigForm : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="OpenWebuiRoutersOllamaOllamaConfigForm" /> class.
        /// </summary>
        /// <param name="oLLAMABASEURLS">oLLAMABASEURLS</param>
        /// <param name="oLLAMAAPICONFIGS">oLLAMAAPICONFIGS</param>
        /// <param name="eNABLEOLLAMAAPI">eNABLEOLLAMAAPI</param>
        [JsonConstructor]
        public OpenWebuiRoutersOllamaOllamaConfigForm(List<string> oLLAMABASEURLS, Object oLLAMAAPICONFIGS, Option<bool?> eNABLEOLLAMAAPI = default)
        {
            OLLAMA_BASE_URLS = oLLAMABASEURLS;
            OLLAMA_API_CONFIGS = oLLAMAAPICONFIGS;
            ENABLE_OLLAMA_APIOption = eNABLEOLLAMAAPI;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets OLLAMA_BASE_URLS
        /// </summary>
        [JsonPropertyName("OLLAMA_BASE_URLS")]
        public List<string> OLLAMA_BASE_URLS { get; set; }

        /// <summary>
        /// Gets or Sets OLLAMA_API_CONFIGS
        /// </summary>
        [JsonPropertyName("OLLAMA_API_CONFIGS")]
        public Object OLLAMA_API_CONFIGS { get; set; }

        /// <summary>
        /// Used to track the state of ENABLE_OLLAMA_API
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> ENABLE_OLLAMA_APIOption { get; private set; }

        /// <summary>
        /// Gets or Sets ENABLE_OLLAMA_API
        /// </summary>
        [JsonPropertyName("ENABLE_OLLAMA_API")]
        public bool? ENABLE_OLLAMA_API { get { return this.ENABLE_OLLAMA_APIOption; } set { this.ENABLE_OLLAMA_APIOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class OpenWebuiRoutersOllamaOllamaConfigForm {\n");
            sb.Append("  OLLAMA_BASE_URLS: ").Append(OLLAMA_BASE_URLS).Append("\n");
            sb.Append("  OLLAMA_API_CONFIGS: ").Append(OLLAMA_API_CONFIGS).Append("\n");
            sb.Append("  ENABLE_OLLAMA_API: ").Append(ENABLE_OLLAMA_API).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="OpenWebuiRoutersOllamaOllamaConfigForm" />
    /// </summary>
    public class OpenWebuiRoutersOllamaOllamaConfigFormJsonConverter : JsonConverter<OpenWebuiRoutersOllamaOllamaConfigForm>
    {
        /// <summary>
        /// Deserializes json to <see cref="OpenWebuiRoutersOllamaOllamaConfigForm" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override OpenWebuiRoutersOllamaOllamaConfigForm Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<List<string>?> oLLAMABASEURLS = default;
            Option<Object?> oLLAMAAPICONFIGS = default;
            Option<bool?> eNABLEOLLAMAAPI = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "OLLAMA_BASE_URLS":
                            oLLAMABASEURLS = new Option<List<string>?>(JsonSerializer.Deserialize<List<string>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "OLLAMA_API_CONFIGS":
                            oLLAMAAPICONFIGS = new Option<Object?>(JsonSerializer.Deserialize<Object>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "ENABLE_OLLAMA_API":
                            eNABLEOLLAMAAPI = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!oLLAMABASEURLS.IsSet)
                throw new ArgumentException("Property is required for class OpenWebuiRoutersOllamaOllamaConfigForm.", nameof(oLLAMABASEURLS));

            if (!oLLAMAAPICONFIGS.IsSet)
                throw new ArgumentException("Property is required for class OpenWebuiRoutersOllamaOllamaConfigForm.", nameof(oLLAMAAPICONFIGS));

            if (oLLAMABASEURLS.IsSet && oLLAMABASEURLS.Value == null)
                throw new ArgumentNullException(nameof(oLLAMABASEURLS), "Property is not nullable for class OpenWebuiRoutersOllamaOllamaConfigForm.");

            if (oLLAMAAPICONFIGS.IsSet && oLLAMAAPICONFIGS.Value == null)
                throw new ArgumentNullException(nameof(oLLAMAAPICONFIGS), "Property is not nullable for class OpenWebuiRoutersOllamaOllamaConfigForm.");

            return new OpenWebuiRoutersOllamaOllamaConfigForm(oLLAMABASEURLS.Value!, oLLAMAAPICONFIGS.Value!, eNABLEOLLAMAAPI);
        }

        /// <summary>
        /// Serializes a <see cref="OpenWebuiRoutersOllamaOllamaConfigForm" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="openWebuiRoutersOllamaOllamaConfigForm"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, OpenWebuiRoutersOllamaOllamaConfigForm openWebuiRoutersOllamaOllamaConfigForm, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, openWebuiRoutersOllamaOllamaConfigForm, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="OpenWebuiRoutersOllamaOllamaConfigForm" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="openWebuiRoutersOllamaOllamaConfigForm"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, OpenWebuiRoutersOllamaOllamaConfigForm openWebuiRoutersOllamaOllamaConfigForm, JsonSerializerOptions jsonSerializerOptions)
        {
            if (openWebuiRoutersOllamaOllamaConfigForm.OLLAMA_BASE_URLS == null)
                throw new ArgumentNullException(nameof(openWebuiRoutersOllamaOllamaConfigForm.OLLAMA_BASE_URLS), "Property is required for class OpenWebuiRoutersOllamaOllamaConfigForm.");

            if (openWebuiRoutersOllamaOllamaConfigForm.OLLAMA_API_CONFIGS == null)
                throw new ArgumentNullException(nameof(openWebuiRoutersOllamaOllamaConfigForm.OLLAMA_API_CONFIGS), "Property is required for class OpenWebuiRoutersOllamaOllamaConfigForm.");

            writer.WritePropertyName("OLLAMA_BASE_URLS");
            JsonSerializer.Serialize(writer, openWebuiRoutersOllamaOllamaConfigForm.OLLAMA_BASE_URLS, jsonSerializerOptions);
            writer.WritePropertyName("OLLAMA_API_CONFIGS");
            JsonSerializer.Serialize(writer, openWebuiRoutersOllamaOllamaConfigForm.OLLAMA_API_CONFIGS, jsonSerializerOptions);
            if (openWebuiRoutersOllamaOllamaConfigForm.ENABLE_OLLAMA_APIOption.IsSet)
                if (openWebuiRoutersOllamaOllamaConfigForm.ENABLE_OLLAMA_APIOption.Value != null)
                    writer.WriteBoolean("ENABLE_OLLAMA_API", openWebuiRoutersOllamaOllamaConfigForm.ENABLE_OLLAMA_APIOption.Value!.Value);
                else
                    writer.WriteNull("ENABLE_OLLAMA_API");
        }
    }
}
