// <auto-generated>
/*
 * Open WebUI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// ProcessTextForm
    /// </summary>
    public partial class ProcessTextForm : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ProcessTextForm" /> class.
        /// </summary>
        /// <param name="name">name</param>
        /// <param name="content">content</param>
        /// <param name="collectionName">collectionName</param>
        [JsonConstructor]
        public ProcessTextForm(string name, string content, Option<string?> collectionName = default)
        {
            Name = name;
            Content = content;
            CollectionNameOption = collectionName;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [JsonPropertyName("name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets Content
        /// </summary>
        [JsonPropertyName("content")]
        public string Content { get; set; }

        /// <summary>
        /// Used to track the state of CollectionName
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> CollectionNameOption { get; private set; }

        /// <summary>
        /// Gets or Sets CollectionName
        /// </summary>
        [JsonPropertyName("collection_name")]
        public string? CollectionName { get { return this.CollectionNameOption; } set { this.CollectionNameOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ProcessTextForm {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Content: ").Append(Content).Append("\n");
            sb.Append("  CollectionName: ").Append(CollectionName).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ProcessTextForm" />
    /// </summary>
    public class ProcessTextFormJsonConverter : JsonConverter<ProcessTextForm>
    {
        /// <summary>
        /// Deserializes json to <see cref="ProcessTextForm" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ProcessTextForm Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> name = default;
            Option<string?> content = default;
            Option<string?> collectionName = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "name":
                            name = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "content":
                            content = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "collection_name":
                            collectionName = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!name.IsSet)
                throw new ArgumentException("Property is required for class ProcessTextForm.", nameof(name));

            if (!content.IsSet)
                throw new ArgumentException("Property is required for class ProcessTextForm.", nameof(content));

            if (name.IsSet && name.Value == null)
                throw new ArgumentNullException(nameof(name), "Property is not nullable for class ProcessTextForm.");

            if (content.IsSet && content.Value == null)
                throw new ArgumentNullException(nameof(content), "Property is not nullable for class ProcessTextForm.");

            return new ProcessTextForm(name.Value!, content.Value!, collectionName);
        }

        /// <summary>
        /// Serializes a <see cref="ProcessTextForm" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="processTextForm"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ProcessTextForm processTextForm, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, processTextForm, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ProcessTextForm" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="processTextForm"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ProcessTextForm processTextForm, JsonSerializerOptions jsonSerializerOptions)
        {
            if (processTextForm.Name == null)
                throw new ArgumentNullException(nameof(processTextForm.Name), "Property is required for class ProcessTextForm.");

            if (processTextForm.Content == null)
                throw new ArgumentNullException(nameof(processTextForm.Content), "Property is required for class ProcessTextForm.");

            writer.WriteString("name", processTextForm.Name);

            writer.WriteString("content", processTextForm.Content);

            if (processTextForm.CollectionNameOption.IsSet)
                if (processTextForm.CollectionNameOption.Value != null)
                    writer.WriteString("collection_name", processTextForm.CollectionName);
                else
                    writer.WriteNull("collection_name");
        }
    }
}
