// <auto-generated>
/*
 * Open WebUI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// ProcessUrlForm
    /// </summary>
    public partial class ProcessUrlForm : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ProcessUrlForm" /> class.
        /// </summary>
        /// <param name="url">url</param>
        /// <param name="collectionName">collectionName</param>
        [JsonConstructor]
        public ProcessUrlForm(string url, Option<string?> collectionName = default)
        {
            Url = url;
            CollectionNameOption = collectionName;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Url
        /// </summary>
        [JsonPropertyName("url")]
        public string Url { get; set; }

        /// <summary>
        /// Used to track the state of CollectionName
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> CollectionNameOption { get; private set; }

        /// <summary>
        /// Gets or Sets CollectionName
        /// </summary>
        [JsonPropertyName("collection_name")]
        public string? CollectionName { get { return this.CollectionNameOption; } set { this.CollectionNameOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ProcessUrlForm {\n");
            sb.Append("  Url: ").Append(Url).Append("\n");
            sb.Append("  CollectionName: ").Append(CollectionName).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ProcessUrlForm" />
    /// </summary>
    public class ProcessUrlFormJsonConverter : JsonConverter<ProcessUrlForm>
    {
        /// <summary>
        /// Deserializes json to <see cref="ProcessUrlForm" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ProcessUrlForm Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> url = default;
            Option<string?> collectionName = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "url":
                            url = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "collection_name":
                            collectionName = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!url.IsSet)
                throw new ArgumentException("Property is required for class ProcessUrlForm.", nameof(url));

            if (url.IsSet && url.Value == null)
                throw new ArgumentNullException(nameof(url), "Property is not nullable for class ProcessUrlForm.");

            return new ProcessUrlForm(url.Value!, collectionName);
        }

        /// <summary>
        /// Serializes a <see cref="ProcessUrlForm" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="processUrlForm"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ProcessUrlForm processUrlForm, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, processUrlForm, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ProcessUrlForm" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="processUrlForm"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ProcessUrlForm processUrlForm, JsonSerializerOptions jsonSerializerOptions)
        {
            if (processUrlForm.Url == null)
                throw new ArgumentNullException(nameof(processUrlForm.Url), "Property is required for class ProcessUrlForm.");

            writer.WriteString("url", processUrlForm.Url);

            if (processUrlForm.CollectionNameOption.IsSet)
                if (processUrlForm.CollectionNameOption.Value != null)
                    writer.WriteString("collection_name", processUrlForm.CollectionName);
                else
                    writer.WriteNull("collection_name");
        }
    }
}
