// <auto-generated>
/*
 * Open WebUI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// QueryDocForm
    /// </summary>
    public partial class QueryDocForm : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="QueryDocForm" /> class.
        /// </summary>
        /// <param name="collectionName">collectionName</param>
        /// <param name="query">query</param>
        /// <param name="k">k</param>
        /// <param name="kReranker">kReranker</param>
        /// <param name="r">r</param>
        /// <param name="hybrid">hybrid</param>
        [JsonConstructor]
        public QueryDocForm(string collectionName, string query, Option<int?> k = default, Option<int?> kReranker = default, Option<decimal?> r = default, Option<bool?> hybrid = default)
        {
            CollectionName = collectionName;
            Query = query;
            KOption = k;
            KRerankerOption = kReranker;
            ROption = r;
            HybridOption = hybrid;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets CollectionName
        /// </summary>
        [JsonPropertyName("collection_name")]
        public string CollectionName { get; set; }

        /// <summary>
        /// Gets or Sets Query
        /// </summary>
        [JsonPropertyName("query")]
        public string Query { get; set; }

        /// <summary>
        /// Used to track the state of K
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> KOption { get; private set; }

        /// <summary>
        /// Gets or Sets K
        /// </summary>
        [JsonPropertyName("k")]
        public int? K { get { return this.KOption; } set { this.KOption = new(value); } }

        /// <summary>
        /// Used to track the state of KReranker
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> KRerankerOption { get; private set; }

        /// <summary>
        /// Gets or Sets KReranker
        /// </summary>
        [JsonPropertyName("k_reranker")]
        public int? KReranker { get { return this.KRerankerOption; } set { this.KRerankerOption = new(value); } }

        /// <summary>
        /// Used to track the state of R
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<decimal?> ROption { get; private set; }

        /// <summary>
        /// Gets or Sets R
        /// </summary>
        [JsonPropertyName("r")]
        public decimal? R { get { return this.ROption; } set { this.ROption = new(value); } }

        /// <summary>
        /// Used to track the state of Hybrid
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> HybridOption { get; private set; }

        /// <summary>
        /// Gets or Sets Hybrid
        /// </summary>
        [JsonPropertyName("hybrid")]
        public bool? Hybrid { get { return this.HybridOption; } set { this.HybridOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class QueryDocForm {\n");
            sb.Append("  CollectionName: ").Append(CollectionName).Append("\n");
            sb.Append("  Query: ").Append(Query).Append("\n");
            sb.Append("  K: ").Append(K).Append("\n");
            sb.Append("  KReranker: ").Append(KReranker).Append("\n");
            sb.Append("  R: ").Append(R).Append("\n");
            sb.Append("  Hybrid: ").Append(Hybrid).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="QueryDocForm" />
    /// </summary>
    public class QueryDocFormJsonConverter : JsonConverter<QueryDocForm>
    {
        /// <summary>
        /// Deserializes json to <see cref="QueryDocForm" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override QueryDocForm Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> collectionName = default;
            Option<string?> query = default;
            Option<int?> k = default;
            Option<int?> kReranker = default;
            Option<decimal?> r = default;
            Option<bool?> hybrid = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "collection_name":
                            collectionName = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "query":
                            query = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "k":
                            k = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "k_reranker":
                            kReranker = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "r":
                            r = new Option<decimal?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (decimal?)null : utf8JsonReader.GetDecimal());
                            break;
                        case "hybrid":
                            hybrid = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!collectionName.IsSet)
                throw new ArgumentException("Property is required for class QueryDocForm.", nameof(collectionName));

            if (!query.IsSet)
                throw new ArgumentException("Property is required for class QueryDocForm.", nameof(query));

            if (collectionName.IsSet && collectionName.Value == null)
                throw new ArgumentNullException(nameof(collectionName), "Property is not nullable for class QueryDocForm.");

            if (query.IsSet && query.Value == null)
                throw new ArgumentNullException(nameof(query), "Property is not nullable for class QueryDocForm.");

            return new QueryDocForm(collectionName.Value!, query.Value!, k, kReranker, r, hybrid);
        }

        /// <summary>
        /// Serializes a <see cref="QueryDocForm" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="queryDocForm"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, QueryDocForm queryDocForm, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, queryDocForm, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="QueryDocForm" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="queryDocForm"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, QueryDocForm queryDocForm, JsonSerializerOptions jsonSerializerOptions)
        {
            if (queryDocForm.CollectionName == null)
                throw new ArgumentNullException(nameof(queryDocForm.CollectionName), "Property is required for class QueryDocForm.");

            if (queryDocForm.Query == null)
                throw new ArgumentNullException(nameof(queryDocForm.Query), "Property is required for class QueryDocForm.");

            writer.WriteString("collection_name", queryDocForm.CollectionName);

            writer.WriteString("query", queryDocForm.Query);

            if (queryDocForm.KOption.IsSet)
                if (queryDocForm.KOption.Value != null)
                    writer.WriteNumber("k", queryDocForm.KOption.Value!.Value);
                else
                    writer.WriteNull("k");

            if (queryDocForm.KRerankerOption.IsSet)
                if (queryDocForm.KRerankerOption.Value != null)
                    writer.WriteNumber("k_reranker", queryDocForm.KRerankerOption.Value!.Value);
                else
                    writer.WriteNull("k_reranker");

            if (queryDocForm.ROption.IsSet)
                if (queryDocForm.ROption.Value != null)
                    writer.WriteNumber("r", queryDocForm.ROption.Value!.Value);
                else
                    writer.WriteNull("r");

            if (queryDocForm.HybridOption.IsSet)
                if (queryDocForm.HybridOption.Value != null)
                    writer.WriteBoolean("hybrid", queryDocForm.HybridOption.Value!.Value);
                else
                    writer.WriteNull("hybrid");
        }
    }
}
