// <auto-generated>
/*
 * Open WebUI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// SetBannersForm
    /// </summary>
    public partial class SetBannersForm : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SetBannersForm" /> class.
        /// </summary>
        /// <param name="banners">banners</param>
        [JsonConstructor]
        public SetBannersForm(List<BannerModel> banners)
        {
            Banners = banners;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Banners
        /// </summary>
        [JsonPropertyName("banners")]
        public List<BannerModel> Banners { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SetBannersForm {\n");
            sb.Append("  Banners: ").Append(Banners).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="SetBannersForm" />
    /// </summary>
    public class SetBannersFormJsonConverter : JsonConverter<SetBannersForm>
    {
        /// <summary>
        /// Deserializes json to <see cref="SetBannersForm" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override SetBannersForm Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<List<BannerModel>?> banners = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "banners":
                            banners = new Option<List<BannerModel>?>(JsonSerializer.Deserialize<List<BannerModel>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!banners.IsSet)
                throw new ArgumentException("Property is required for class SetBannersForm.", nameof(banners));

            if (banners.IsSet && banners.Value == null)
                throw new ArgumentNullException(nameof(banners), "Property is not nullable for class SetBannersForm.");

            return new SetBannersForm(banners.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="SetBannersForm" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="setBannersForm"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, SetBannersForm setBannersForm, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, setBannersForm, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="SetBannersForm" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="setBannersForm"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, SetBannersForm setBannersForm, JsonSerializerOptions jsonSerializerOptions)
        {
            if (setBannersForm.Banners == null)
                throw new ArgumentNullException(nameof(setBannersForm.Banners), "Property is required for class SetBannersForm.");

            writer.WritePropertyName("banners");
            JsonSerializer.Serialize(writer, setBannersForm.Banners, jsonSerializerOptions);
        }
    }
}
