// <auto-generated>
/*
 * Open WebUI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// SetDefaultSuggestionsForm
    /// </summary>
    public partial class SetDefaultSuggestionsForm : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SetDefaultSuggestionsForm" /> class.
        /// </summary>
        /// <param name="suggestions">suggestions</param>
        [JsonConstructor]
        public SetDefaultSuggestionsForm(List<PromptSuggestion> suggestions)
        {
            Suggestions = suggestions;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Suggestions
        /// </summary>
        [JsonPropertyName("suggestions")]
        public List<PromptSuggestion> Suggestions { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SetDefaultSuggestionsForm {\n");
            sb.Append("  Suggestions: ").Append(Suggestions).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="SetDefaultSuggestionsForm" />
    /// </summary>
    public class SetDefaultSuggestionsFormJsonConverter : JsonConverter<SetDefaultSuggestionsForm>
    {
        /// <summary>
        /// Deserializes json to <see cref="SetDefaultSuggestionsForm" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override SetDefaultSuggestionsForm Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<List<PromptSuggestion>?> suggestions = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "suggestions":
                            suggestions = new Option<List<PromptSuggestion>?>(JsonSerializer.Deserialize<List<PromptSuggestion>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!suggestions.IsSet)
                throw new ArgumentException("Property is required for class SetDefaultSuggestionsForm.", nameof(suggestions));

            if (suggestions.IsSet && suggestions.Value == null)
                throw new ArgumentNullException(nameof(suggestions), "Property is not nullable for class SetDefaultSuggestionsForm.");

            return new SetDefaultSuggestionsForm(suggestions.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="SetDefaultSuggestionsForm" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="setDefaultSuggestionsForm"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, SetDefaultSuggestionsForm setDefaultSuggestionsForm, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, setDefaultSuggestionsForm, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="SetDefaultSuggestionsForm" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="setDefaultSuggestionsForm"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, SetDefaultSuggestionsForm setDefaultSuggestionsForm, JsonSerializerOptions jsonSerializerOptions)
        {
            if (setDefaultSuggestionsForm.Suggestions == null)
                throw new ArgumentNullException(nameof(setDefaultSuggestionsForm.Suggestions), "Property is required for class SetDefaultSuggestionsForm.");

            writer.WritePropertyName("suggestions");
            JsonSerializer.Serialize(writer, setDefaultSuggestionsForm.Suggestions, jsonSerializerOptions);
        }
    }
}
