// <auto-generated>
/*
 * Open WebUI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// ToolModel
    /// </summary>
    public partial class ToolModel : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ToolModel" /> class.
        /// </summary>
        /// <param name="id">id</param>
        /// <param name="userId">userId</param>
        /// <param name="name">name</param>
        /// <param name="content">content</param>
        /// <param name="specs">specs</param>
        /// <param name="meta">meta</param>
        /// <param name="updatedAt">updatedAt</param>
        /// <param name="createdAt">createdAt</param>
        /// <param name="accessControl">accessControl</param>
        [JsonConstructor]
        public ToolModel(string id, string userId, string name, string content, List<Object> specs, ToolMeta meta, int updatedAt, int createdAt, Option<Object?> accessControl = default)
        {
            Id = id;
            UserId = userId;
            Name = name;
            Content = content;
            Specs = specs;
            Meta = meta;
            UpdatedAt = updatedAt;
            CreatedAt = createdAt;
            AccessControlOption = accessControl;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [JsonPropertyName("id")]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets UserId
        /// </summary>
        [JsonPropertyName("user_id")]
        public string UserId { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [JsonPropertyName("name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets Content
        /// </summary>
        [JsonPropertyName("content")]
        public string Content { get; set; }

        /// <summary>
        /// Gets or Sets Specs
        /// </summary>
        [JsonPropertyName("specs")]
        public List<Object> Specs { get; set; }

        /// <summary>
        /// Gets or Sets Meta
        /// </summary>
        [JsonPropertyName("meta")]
        public ToolMeta Meta { get; set; }

        /// <summary>
        /// Gets or Sets UpdatedAt
        /// </summary>
        [JsonPropertyName("updated_at")]
        public int UpdatedAt { get; set; }

        /// <summary>
        /// Gets or Sets CreatedAt
        /// </summary>
        [JsonPropertyName("created_at")]
        public int CreatedAt { get; set; }

        /// <summary>
        /// Used to track the state of AccessControl
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Object?> AccessControlOption { get; private set; }

        /// <summary>
        /// Gets or Sets AccessControl
        /// </summary>
        [JsonPropertyName("access_control")]
        public Object? AccessControl { get { return this.AccessControlOption; } set { this.AccessControlOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ToolModel {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  UserId: ").Append(UserId).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Content: ").Append(Content).Append("\n");
            sb.Append("  Specs: ").Append(Specs).Append("\n");
            sb.Append("  Meta: ").Append(Meta).Append("\n");
            sb.Append("  UpdatedAt: ").Append(UpdatedAt).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  AccessControl: ").Append(AccessControl).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ToolModel" />
    /// </summary>
    public class ToolModelJsonConverter : JsonConverter<ToolModel>
    {
        /// <summary>
        /// Deserializes json to <see cref="ToolModel" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ToolModel Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> id = default;
            Option<string?> userId = default;
            Option<string?> name = default;
            Option<string?> content = default;
            Option<List<Object>?> specs = default;
            Option<ToolMeta?> meta = default;
            Option<int?> updatedAt = default;
            Option<int?> createdAt = default;
            Option<Object?> accessControl = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "id":
                            id = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "user_id":
                            userId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "name":
                            name = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "content":
                            content = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "specs":
                            specs = new Option<List<Object>?>(JsonSerializer.Deserialize<List<Object>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "meta":
                            meta = new Option<ToolMeta?>(JsonSerializer.Deserialize<ToolMeta>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "updated_at":
                            updatedAt = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "created_at":
                            createdAt = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "access_control":
                            accessControl = new Option<Object?>(JsonSerializer.Deserialize<Object>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!id.IsSet)
                throw new ArgumentException("Property is required for class ToolModel.", nameof(id));

            if (!userId.IsSet)
                throw new ArgumentException("Property is required for class ToolModel.", nameof(userId));

            if (!name.IsSet)
                throw new ArgumentException("Property is required for class ToolModel.", nameof(name));

            if (!content.IsSet)
                throw new ArgumentException("Property is required for class ToolModel.", nameof(content));

            if (!specs.IsSet)
                throw new ArgumentException("Property is required for class ToolModel.", nameof(specs));

            if (!meta.IsSet)
                throw new ArgumentException("Property is required for class ToolModel.", nameof(meta));

            if (!updatedAt.IsSet)
                throw new ArgumentException("Property is required for class ToolModel.", nameof(updatedAt));

            if (!createdAt.IsSet)
                throw new ArgumentException("Property is required for class ToolModel.", nameof(createdAt));

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class ToolModel.");

            if (userId.IsSet && userId.Value == null)
                throw new ArgumentNullException(nameof(userId), "Property is not nullable for class ToolModel.");

            if (name.IsSet && name.Value == null)
                throw new ArgumentNullException(nameof(name), "Property is not nullable for class ToolModel.");

            if (content.IsSet && content.Value == null)
                throw new ArgumentNullException(nameof(content), "Property is not nullable for class ToolModel.");

            if (specs.IsSet && specs.Value == null)
                throw new ArgumentNullException(nameof(specs), "Property is not nullable for class ToolModel.");

            if (meta.IsSet && meta.Value == null)
                throw new ArgumentNullException(nameof(meta), "Property is not nullable for class ToolModel.");

            if (updatedAt.IsSet && updatedAt.Value == null)
                throw new ArgumentNullException(nameof(updatedAt), "Property is not nullable for class ToolModel.");

            if (createdAt.IsSet && createdAt.Value == null)
                throw new ArgumentNullException(nameof(createdAt), "Property is not nullable for class ToolModel.");

            return new ToolModel(id.Value!, userId.Value!, name.Value!, content.Value!, specs.Value!, meta.Value!, updatedAt.Value!.Value!, createdAt.Value!.Value!, accessControl);
        }

        /// <summary>
        /// Serializes a <see cref="ToolModel" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="toolModel"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ToolModel toolModel, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, toolModel, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ToolModel" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="toolModel"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ToolModel toolModel, JsonSerializerOptions jsonSerializerOptions)
        {
            if (toolModel.Id == null)
                throw new ArgumentNullException(nameof(toolModel.Id), "Property is required for class ToolModel.");

            if (toolModel.UserId == null)
                throw new ArgumentNullException(nameof(toolModel.UserId), "Property is required for class ToolModel.");

            if (toolModel.Name == null)
                throw new ArgumentNullException(nameof(toolModel.Name), "Property is required for class ToolModel.");

            if (toolModel.Content == null)
                throw new ArgumentNullException(nameof(toolModel.Content), "Property is required for class ToolModel.");

            if (toolModel.Specs == null)
                throw new ArgumentNullException(nameof(toolModel.Specs), "Property is required for class ToolModel.");

            if (toolModel.Meta == null)
                throw new ArgumentNullException(nameof(toolModel.Meta), "Property is required for class ToolModel.");

            writer.WriteString("id", toolModel.Id);

            writer.WriteString("user_id", toolModel.UserId);

            writer.WriteString("name", toolModel.Name);

            writer.WriteString("content", toolModel.Content);

            writer.WritePropertyName("specs");
            JsonSerializer.Serialize(writer, toolModel.Specs, jsonSerializerOptions);
            writer.WritePropertyName("meta");
            JsonSerializer.Serialize(writer, toolModel.Meta, jsonSerializerOptions);
            writer.WriteNumber("updated_at", toolModel.UpdatedAt);

            writer.WriteNumber("created_at", toolModel.CreatedAt);

            if (toolModel.AccessControlOption.IsSet)
                if (toolModel.AccessControlOption.Value != null)
                {
                    writer.WritePropertyName("access_control");
                    JsonSerializer.Serialize(writer, toolModel.AccessControl, jsonSerializerOptions);
                }
                else
                    writer.WriteNull("access_control");
        }
    }
}
